pipeline {
    agent any

    stages {
        stage('Ejecutar pruebas') {
            steps {
                dir('template-main/RA5/RA5_1') {
                    sh 'python3 -m unittest test_calculadora.py'
                }
            }
        }
    }

    post {
        success {
            echo 'Pruebas ejecutadas correctamente.'
        }
        failure {
            echo 'Fallo en la pipeline.'
        }
    }
}
