apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: web2
  name: web2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web2
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: web2
    spec:
      containers:
        - image: nginx
          name: web2
      restartPolicy: Always
