---
- name: Actualizar sistema e instalar Apache
  hosts: ubuntu
  become: yes
  tasks:
    - name: Update y upgrade del sistema
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar Apache
      apt:
        name: apache2
        state: present
