---
- name: Crear index.html y reiniciar Apache
  hosts: ubuntu
  become: yes
  tasks:
    - name: Subir index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted

    - name: Verificar mensaje
      command: curl http://localhost
      register: resultado

    - name: Mostrar resultado
      debug:
        var: resultado.stdout
