---
- name: Crear index.html y reiniciar Apache
  hosts: ubuntu
  become: yes
  tasks:
    - name: Crear index.html
      copy:
        dest: /var/www/html/index.html
        content: "Ansible rocks"

    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted

    - name: Verificar el mensaje
      command: curl http://localhost
      register: resultado

    - name: Mostrar el resultado
      debug:
        var: resultado.stdout
