Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.hostname = "ubuntu-ansible"
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook_update_apache.yml"
    ansible.inventory_path = "ansible/inventory.ini"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook_index_html.yml"
    ansible.inventory_path = "ansible/inventory.ini"
  end
end
